/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package javaapplication1;

import java.awt.Toolkit;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author arvsa
 */
public class Landing extends javax.swing.JFrame {

    /**
     * Creates new form Landing
     */
    public Landing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        wel = new javax.swing.JLabel();
        f1 = new javax.swing.JLabel();
        f2 = new javax.swing.JLabel();
        f3 = new javax.swing.JLabel();
        f4 = new javax.swing.JLabel();
        f5 = new javax.swing.JLabel();
        f6 = new javax.swing.JLabel();
        f7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        getStarted = new javaapplication1.FButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 51));
        setSize(new java.awt.Dimension(410, 635));

        jPanel1.setBackground(new java.awt.Color(242, 249, 241));
        jPanel1.setForeground(new java.awt.Color(242, 249, 241));
        jPanel1.setPreferredSize(new java.awt.Dimension(416, 697));

        wel.setBackground(new java.awt.Color(255, 255, 255));
        wel.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        wel.setForeground(new java.awt.Color(92, 113, 94));
        wel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wel.setText("Welcome To");
        wel.setToolTipText("");

        f1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        f1.setForeground(new java.awt.Color(92, 113, 94));
        f1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f1.setText("PrimeAge empowers elders to achieve");

        f2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        f2.setForeground(new java.awt.Color(92, 113, 94));
        f2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f2.setText("achieve optimal well-being through");

        f3.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        f3.setForeground(new java.awt.Color(92, 113, 94));
        f3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f3.setText("active lifestyle, balanced nutrition,");

        f4.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        f4.setForeground(new java.awt.Color(92, 113, 94));
        f4.setText("preventive care, and mindfulness. We ");

        f5.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        f5.setForeground(new java.awt.Color(92, 113, 94));
        f5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f5.setText("We foster healthy aging with tailored");

        f6.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        f6.setForeground(new java.awt.Color(92, 113, 94));
        f6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f6.setText("guidance, promoting dignity, strength,");

        f7.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        f7.setForeground(new java.awt.Color(92, 113, 94));
        f7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f7.setText("and fulfillment at every stage of life.");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\arvsa\\Documents\\NetBeansProjects\\PrimeAge_Semis\\src\\main\\java\\com\\mycompany\\primeage_semis\\PrimeAgeLogo 1 (1).png")); // NOI18N

        getStarted.setBackground(new java.awt.Color(92, 113, 94));
        getStarted.setText("Get Started");
        getStarted.setFillClick(new java.awt.Color(153, 153, 153));
        getStarted.setFillOriginal(new java.awt.Color(92, 113, 94));
        getStarted.setFillOver(new java.awt.Color(92, 113, 94));
        getStarted.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        getStarted.setLineOriginal(new java.awt.Color(255, 255, 255));
        getStarted.setLineOver(new java.awt.Color(255, 255, 255));
        getStarted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getStartedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(f2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(getStarted, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(wel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(f1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(f3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f7)
                .addGap(18, 18, 18)
                .addComponent(getStarted, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getStartedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getStartedActionPerformed
        Login sec = new Login();
        sec.setVisible(true);
        sec.pack();
        sec.setLocationRelativeTo(null);
        
        this.setVisible(false);
    }//GEN-LAST:event_getStartedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException ignored) {
            Toolkit.getDefaultToolkit().beep(); // Notify the user
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            ex.printStackTrace(); // Log the error to understand the issue
        }
        
        java.awt.EventQueue.invokeLater(() -> {
            new Landing().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel f3;
    private javax.swing.JLabel f4;
    private javax.swing.JLabel f5;
    private javax.swing.JLabel f6;
    private javax.swing.JLabel f7;
    private javaapplication1.FButton getStarted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel wel;
    // End of variables declaration//GEN-END:variables
}
